name: supa_architecture
description: Architecture library for Supa Flutter applications
version: 1.10.0-rc.4
homepage: https://github.supa.vn

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  aad_oauth: ^1.0.0
  bloc: ^9.0.0
  device_info_plus: ^11.0.0
  dio: ^5.7.0
  equatable: ^2.0.0
  file_picker: ^10.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_messaging: ^15.0.0
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.0.0
  flutter_secure_storage: ^9.2.0
  get_it: ^8.0.0
  go_router: ^15.0.0
  google_sign_in: ^6.0.0
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  image_picker: ^1.1.0
  infinite_scroll_pagination: ^4.1.0
  injectable: ^2.5.0
  intl: ^0.19.0
  local_auth: ^2.0.0
  open_file: ^3.5.0
  package_info_plus: ^8.0.0
  path: ^1.0.0
  path_provider: ^2.0.0
  plugin_platform_interface: ^2.0.0
  reactive_forms: ^17.0.0
  sign_in_with_apple: ^6.0.0
  supa_carbon_icons: ^0.0.1+6
  url_launcher: ^6.0.0
  web: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: vn.supa.supa_architecture
        pluginClass: SupaArchitecturePlugin
      ios:
        pluginClass: SupaArchitecturePlugin
      linux:
        pluginClass: SupaArchitecturePlugin
      macos:
        pluginClass: SupaArchitecturePlugin
      windows:
        pluginClass: SupaArchitecturePluginCApi
      web:
        pluginClass: SupaArchitectureWeb
        fileName: supa_architecture_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/supa_architecture/assets/images/empty_state.png
    - packages/supa_architecture/assets/images/image_placeholder.png
    - packages/supa_architecture/assets/images/page_forbidden.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific variants, see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this flutter section. Each entry in this list should have a
  # family key with the font family name, and a fonts key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
