name: supa_architecture
description: >
  A comprehensive set of tools and utilities designed to streamline the development of Flutter applications.
version: 0.0.1+preview.5
homepage: https://github.com/thanhtunguet/supa_architecture

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^4.0.0
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  flutter_secure_storage: ^9.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path: ^1.0.0
  path_provider: ^2.0.0
  rxdart: ^0.28.0
  go_router: ^14.0.0
  url_launcher: ^6.0.0
  equatable: ^2.0.0
  logging: ^1.2.0
  flutter_dotenv: ^5.0.0
  aad_oauth: ^1.0.0
  google_sign_in: ^6.0.0
  sign_in_with_apple: ^6.0.0
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  riverpod: ^2.0.0
  supa_carbon_icons: ^0.0.1+4
  pretty_dio_logger: ^1.0.0
  get_it: ^7.0.0
  injectable: ^2.0.0
  local_auth: ^2.0.0
  device_info_plus: ^9.0.0
  intl: ^0.19.0
  recaptcha_enterprise_flutter: ^18.0.0
  reactive_forms: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  sentry_flutter: ^8.6.0
  toastification: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
